# Site settings
title: DramaBarn
email: dramasoc@yusu.org
description: >
  University of York Drama Soc's technical equipment stock
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dramabarn.github.io/equipment/." # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript
