# Site settings
title: DramaBarn
email: dramasoc@yusu.org
description: >
  University of York Drama Soc's technical equipment stock
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://equipment.yorkdramasoc.com/" # the base hostname & protocol for your site
#url: "localhost:4000" # local dev env

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript

sass:
  sass_dir: _sass
