# Site settings
title: DramaBarn
email: dramasoc@yusu.org
description: >
  University of York Drama Soc's technical equipment stock
baseurl: "/equipment" # the subpath of your site, e.g. /blog
url: "https://equipment.yorkdramasoc.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript

sass:
  sass_dir: _sass
